window.STATE =
{
  "slug": "block-blast-tma",
  "dir": "2026-09-08-block-blast-tma--wip",
  "title": "Block Blast — Telegram Mini App",
  "mode": "semi",
  "depth": "normal",
  "polish": null,
  "tier": "T2",
  "briefFile": "2026-09-08-brief.md",
  "memoryFile": "CLAUDE.md",
  "skillDir": "C:\\Users\\user\\.claude\\skills\\autopilot",
  "startedAt": "2026-09-08T10:21:12+03:00",
  "updatedAt": "2026-09-08T15:23:32+03:00",
  "finishedAt": null,
  "stages": [
    { "id": "preflight", "status": "done", "startedAt": "2026-09-08T10:21:12+03:00", "finishedAt": "2026-09-08T10:23:40+03:00" },
    { "id": "manifest",  "status": "done", "startedAt": "2026-09-08T10:23:40+03:00", "finishedAt": "2026-09-08T10:36:15+03:00" },
    { "id": "briefing",  "status": "done", "startedAt": "2026-09-08T10:23:40+03:00", "finishedAt": "2026-09-08T10:36:15+03:00" },
    { "id": "spec",      "status": "done", "startedAt": "2026-09-08T10:36:15+03:00", "finishedAt": "2026-09-08T10:48:53+03:00" },
    { "id": "plan",      "status": "done", "startedAt": "2026-09-08T10:48:53+03:00", "finishedAt": "2026-09-08T10:54:23+03:00", "note": "7 тасков, ярус T2" },
    { "id": "build",     "status": "done", "startedAt": "2026-09-08T10:54:23+03:00", "finishedAt": "2026-09-08T15:23:32+03:00", "note": "7 из 7 тасков готово" },
    { "id": "review",    "status": "done", "startedAt": "2026-09-08T10:55:42+03:00", "finishedAt": "2026-09-08T15:23:32+03:00", "note": "проверено 7 из 7" },
    { "id": "final",     "status": "active", "startedAt": "2026-09-08T15:23:32+03:00" }
  ],
  "requirements": {
    "total": 46, "done": 40, "inTicket": 0, "inSpec": 0,
    "placeholder": 0, "deferred": 6, "dropped": 0
  },
  "tickets": [
    { "id": "01", "title": "Ядро игровой логики: поле, фигуры, очки",
      "requirements": ["R01","R03","R04","R06","R07","R08","R09","R10","R10.1","R11","R23"],
      "blockedBy": [], "wave": 1, "zone": ["game/board.js","game/shapes.js","game/score.js"],
      "status": "done", "startedAt": "2026-09-08T10:55:42+03:00", "finishedAt": "2026-09-08T11:09:07+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": ["package.json","game/board.js","game/board.test.js","game/shapes.js","game/shapes.test.js","game/score.js","game/score.test.js"],
      "tests": { "passed": 17, "failed": 0 }, "commit": "4eeee3b",
      "concerns": ["game/shapes.test.js — тест «без поворота» проверяет иммутабельность каталога, а не факт отсутствия поворота", "game/board.js — заполненность строки/столбца проверяется двумя разными способами вместо одной общей функции"] },
    { "id": "02", "title": "Рендеринг, ввод и подсказка",
      "requirements": ["R05","R05.1","R05.2","R15","R17","R18","R19","R42"],
      "blockedBy": ["01"], "wave": 2, "zone": ["ui/render.js","ui/input.js","ui/animations.js","style.css","index.html"],
      "status": "done", "startedAt": "2026-09-08T11:02:46+03:00", "finishedAt": "2026-09-08T11:22:20+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": ["index.html","style.css","ui/render.js","ui/input.js","ui/input.test.js","ui/animations.js"],
      "tests": { "passed": 23, "failed": 0 }, "commit": "5620651",
      "concerns": ["ui/render.js и ui/input.js — расчёт boundingBox фигуры продублирован (boundsOf/shapeBounds) вместо общей функции"] },
    { "id": "03", "title": "Персистентность и мост к Telegram",
      "requirements": ["R02","R12","R12.1","R12.2","R22","R22.1","R24","R25","R26","R28","R30","R46i"],
      "blockedBy": ["01"], "wave": 2, "zone": ["telegram/bridge.js","game/persistence.js"],
      "status": "done", "startedAt": "2026-09-08T11:02:46+03:00", "finishedAt": "2026-09-08T11:35:12+03:00",
      "retries": 0, "repairs": 1,
      "repairFindings": ["DEFAULT_GAME_URL — правдоподобный, но выдуманный URL бота вместо видимого плейсхолдера (invented fact, blocking)"],
      "handoffs": 0,
      "files": ["telegram/bridge.js","telegram/bridge.test.js","game/persistence.js","game/persistence.test.js"],
      "tests": { "passed": 44, "failed": 0 }, "commit": "6635964",
      "concerns": ["onThemeChange — метод сверх исходных Границ спецификации, добавлен ради R22.1, внесён в interfaces.md"] },
    { "id": "04", "title": "Экран Game Over и звук",
      "requirements": ["R20","R21","R27"],
      "blockedBy": ["02","03"], "wave": 3, "zone": ["ui/gameover.js","ui/sound.js","assets/sounds/"],
      "status": "done", "startedAt": "2026-09-08T11:36:10+03:00", "finishedAt": "2026-09-08T12:21:07+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": ["ui/gameover.js","ui/gameover.test.js","ui/sound.js","ui/sound.test.js","assets/sounds/click.wav","assets/sounds/line-clear.wav","assets/sounds/game-over.wav"],
      "tests": { "passed": 83, "failed": 0 }, "commit": "cce6339",
      "concerns": ["ui/gameover.js и ui/sound.js — тексты/метки зашиты на русском без шва для i18n, нужно закрыть в таске 07", "ui/gameover.test.js и ui/sound.test.js — фейковый DOM продублирован в двух файлах вместо общего хелпера"] },
    { "id": "05", "title": "Языки и ежедневный челлендж",
      "requirements": ["R14","R14.1","R14.2","R44","R44.1"],
      "blockedBy": ["01","03"], "wave": 3, "zone": ["i18n/","game/challenges.js"],
      "status": "done", "startedAt": "2026-09-08T11:36:10+03:00", "finishedAt": "2026-09-08T11:46:33+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": ["i18n/index.js","i18n/index.test.js","game/challenges.js","game/challenges.test.js"],
      "tests": { "passed": 82, "failed": 0 }, "commit": "22b8d3a" },
    { "id": "06", "title": "Донат через Stars и Telegram-бот",
      "requirements": ["R02","R31","R33","R35","R39","R43","R43.1","R43.2"],
      "blockedBy": ["02","03"], "wave": 3, "zone": ["bot/","api/create-invoice.js","api/telegram-webhook.js","ui/donate.js"],
      "status": "done", "startedAt": "2026-09-08T11:36:10+03:00", "finishedAt": "2026-09-08T11:46:33+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": [".env.example","api/create-invoice.js","api/create-invoice.test.js","api/telegram-webhook.js","bot/bot-logic.js","bot/bot-logic.test.js","ui/donate.js"],
      "tests": { "passed": 82, "failed": 0 }, "commit": "4403538",
      "concerns": ["bot/bot-logic.js и api/create-invoice.js — вызов Telegram Bot API продублирован вместо общего хелпера", "DEFAULT_GAME_URL продублирован как отдельная константа вместо переиспользования из telegram/bridge.js"] },
    { "id": "07", "title": "Интеграция, деплой и инструкция",
      "requirements": ["R34","R36","R38","R40","R41"],
      "blockedBy": ["04","05","06"], "wave": 4, "zone": ["app.js","vercel.json",".env.example","README-deploy.md"],
      "status": "done", "startedAt": "2026-09-08T12:21:07+03:00", "finishedAt": "2026-09-08T15:23:32+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": ["app.js","config.js","config.test.js","api/config.js","api/telegram-webhook.js","index.html","style.css",".env.example","vercel.json","README-deploy.md"],
      "tests": { "passed": 88, "failed": 0 }, "commit": "f176b6f/6d47b82",
      "concerns": ["ui/donate.js экспортирует STARS_AMOUNTS, но app.js берёт номиналы через отдельный /api/config — константа осталась неиспользуемой, два источника правды", "app.js использует только первый настроенный номинал доната, остальные не показываются", "промежуточный git push/squash сделан пользователем самостоятельно (его репозиторий, его решение) — не действие сборки"] }
  ],
  "singlePass": null,
  "tests": { "passed": 88, "failed": 0 },
  "debt": { "placeholders": ["GAME_URL — узнается после деплоя", "STARS_AMOUNTS — номиналы доната, пользователь не называл"], "assumptions": [], "emptyEnv": ["GAME_URL", "STARS_AMOUNTS"] },
  "additions": [],
  "coverage": {
    "missing": 0,
    "halfCovered": 2,
    "halfCoveredFixed": ["R20 — названы все 3 звука явно", "R17 — измеримый критерий отступов и мелких элементов"],
    "notInBrief": 6,
    "notInBriefNote": "все с родителем (R##.n / явное инженерное решение), проверено на A## без родителя — таких нет"
  },
  "concerns": [
    "T01 game/shapes.test.js — тест «без поворота» проверяет иммутабельность каталога, а не отсутствие поворота",
    "T01 game/board.js — заполненность строки/столбца проверяется двумя разными способами вместо одной общей функции",
    "T02 ui/render.js и ui/input.js — расчёт boundingBox фигуры продублирован вместо общей функции",
    "T03 telegram/bridge.js — onThemeChange добавлен сверх исходных Границ спецификации ради R22.1 (обоснованно, внесено в interfaces.md)",
    "T06 bot/bot-logic.js и api/create-invoice.js — вызов Telegram Bot API продублирован вместо общего хелпера",
    "T06 DEFAULT_GAME_URL продублирован как отдельная константа вместо переиспользования из telegram/bridge.js",
    "T04 ui/gameover.test.js и ui/sound.test.js — фейковый DOM продублирован вместо общего тестового хелпера",
    "T07 ui/gameover.js — тексты внутри модуля (кнопка «Поделиться» и др.) так и остались зашиты на русском, i18n-шов не заведён; app.js подменяет отображаемый текст постфактум, но shareResult отправляет русский текст независимо от языка",
    "T07 ui/donate.js экспортирует неиспользуемый STARS_AMOUNTS — номиналы реально идут через /api/config, два источника правды",
    "T07 донат использует только первый настроенный номинал Stars, остальные не предлагаются пользователю"
  ],
  "reviewers": { "manifestSpec": "a6550598d12bbf793", "craft": "aa7d168dd3cb5cd34" },
  "blind": null
}
